### ISSUE TITLE
Unarchive subscribers on already in list exception

### ISSUE THREAD

**Issue by cyrillbolliger** [grueneschweiz/mailchimpservice#34]
The riddle about 
https://github.com/grueneschweiz/mailchimpservice/blob/1f68fe379a0c8553dafc309c739ceda9447504b1/app/Synchronizer/CrmToMailchimpSynchronizer.php#L532-L545
is not yet fully solved. However the condition (L536) has never been met in the past year. We did however find out, that for some contacts the error (L544) was triggered, because the contacts were archived. So we should *unarchive* those.

**Comment by cyrillbolliger** [comment]
Possible cause for the error:
- a duplicate entry of the person (a@mail.com) is made in webling, but with a different email address (b@mail.com).
- the duplicate is synced to mailchimp, so a new record is created in mailchimp. (b@mail.com)
- the duplicate is deleted in webling. up on synchronization, the new record in mailchimp is archived. (b@mail.com)
- the email address of the original record in webling (a@mail.com) is changed to the new email address (b@mail.com)
- the synchronization now fails, because b@mail.com is already in mailchimp's list, but as an archived contact.

**Comment by sandrotanner** [comment]
🕵️
